### ISSUE TITLE
Opening places results in a fatal crash

### ISSUE THREAD

**Issue by boynedmaster** [CloneTrooper1019/Roblox-Studio-Mod-Manager#12]
Hello,

Ever since some new update, trying to open any place results in a fatal crash.

![](https://i.imgur.com/vGGErHo.png)

I cannot test with the old home screen because of #11. This renders the program almost completely worthless.

**Comment by CloneTrooper1019** [comment]
Roblox unfortunately broke the old screen, you're forced to have it on now :(

**Comment by boynedmaster** [comment]
Closing this issue in that case, but because of #11, this program is now useless.

**Comment by CloneTrooper1019** [comment]
I'll try to look into this further.

**Comment by boynedmaster** [comment]
I have no direct access to talk to Roblox (I have not yet been accepted into the developer forum), and info@roblox.com is where reports go to die.
