### ISSUE TITLE
Possibly unwanted mods in the sample mod

### ISSUE THREAD

**Issue by boynedmaster** [CloneTrooper1019/Roblox-Studio-Mod-Manager#13]
I'm not sure that the sample mod works or if this is a valid concern (I don't use RSMM for mods, I use it because it updating Roblox Studio doesn't kill my internet like the real Studio does), but all the code past this line is stuff I wouldn't have known existed if I didn't look at the source code. I believe this isn't included in the default build, but someone may skim the mod and believe it's useful (the CoreScript thing), and not know what it also comes with. 

It contains an automatic inbox replier and an automatic friend request denier. Sure @CloneTrooper1019 might find these useful, but it's really something that shouldn't be in this repository. Perhaps the sample mod should be replaced with an example of something useless just for demonstration of how you would make mods?

**Comment by CloneTrooper1019** [comment]
Thanks for expressing the concern, I was meaning to remove it a few months ago but I finally got around to it today.
