### ISSUE TITLE
fmod.dll not found

### ISSUE THREAD

**Issue by 2005chaddyg** [CloneTrooper1019/Roblox-Studio-Mod-Manager#14]
When i run roblox studio with this it says "The code execution cannot proceed because fmod.dll was not found.

**Comment by CloneTrooper1019** [comment]
Something may have gone wrong with the extraction. Try checking the "Force Client Rebuild" option and see if it fixes itself.

**Comment by CloneTrooper1019** [comment]
Closing this thread as OP seems to be inactive.
