### ISSUE TITLE
Flag search does not filter scanned FVariables

### ISSUE THREAD

**Issue by EchoReaper** [CloneTrooper1019/Roblox-Studio-Mod-Manager#15]
When I scan for new FVariables, they always show up in the list regardless of what I put in the search filter. They will be ignored by the filter until I re-open the FVariable editor window.

Repro steps:
- Wait for Roblox to add more flags to the exe
- Update Studio
- Open FVariable Editor
- Run FVariable Scan
- Type something like "asdsadfsdf" into the search filter

Expected result:
Nothing shows up because no flags match that filter

Actual result:
Any new flag picked up by the FVariable scan is displayed in list, ignoring filter

**Comment by CloneTrooper1019** [comment]
I just released the new flag editor. Scans shouldn't be relevant to this version anymore, so I will close this ticket.

Let me know if you see any issues with the new flag editor.
