### ISSUE TITLE
Executable doesn't do anything when starting

### ISSUE THREAD

**Issue by evaera** [CloneTrooper1019/Roblox-Studio-Mod-Manager#17]
Hi there, I just downloaded the latest version of RobloxStudioModManager.exe, and upon running the executable, absolutely nothing happens. No window pops up, I get no error message, just my mouse turns to a circular loading icon for a second, then nothing happens.

- I don't use any third party anti-virus
- I turned off Windows Defender real-time protection
- I tried running as Administrator
- I tried running both the single executable and the executable from the zip file

Operating system: Windows 10 (10.0.16299)

I think I have used an older version of this program a while ago. Are there any old settings saved that I could clear out could be making it crash on run?

**Comment by LucasWolschick** [comment]
I can confirm this issue still persists. After the last one or two commits that updated the executable, the mod manager stopped working completely, after which I stopped using it and dug back up the studio executable.

I can't find any error logs or anything related to that.

I'm using the latest Windows 10 version (update 1803).

**Comment by LucasWolschick** [comment]
Follow-up to my last message:
I cleaned up the registry keys the mod manager uses (or at least, used), downloaded it again and it seems to work fine now.

Perhaps it's something regarding registry cleanup?

**Comment by CloneTrooper1019** [comment]
I've heard this report from a few people now. This is definitely very weird.
I'll look into it when I have the chance.

**Comment by Rocky28447** [comment]
This issue is still a problem for me. It's been months and there's been no word about a fix. What's the deal?

**Comment by LucasWolschick** [comment]
I fixed it at that time by opening the registry and deleting every key/value associated with the app. Open the search menu and look for "RobloxStudioModManager" (no quotes). Delete everything you find until there are no more hits.

**Comment by CloneTrooper1019** [comment]
Alright hey everyone. I have released a patch that attempts to combat this issue. Sorry for the delay.

Given that the problem seems to be occurring during the program's initial launch, I suspect that it has something to do with a registry key that it tries to access. I have added some safe-guards to hopefully prevent this from happening.

https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/commit/c83ec94f5afef82dae819f08c8126860d27deb8a

If the issue persists for you @Rocky28447, please let me know.
