### ISSUE TITLE
RSMM did not install new LuaPackages to content folder on upgrade

### ISSUE THREAD

**Issue by EchoReaper** [CloneTrooper1019/Roblox-Studio-Mod-Manager#20]
A new folder called "LuaPackages" was added to the content folder of new versions of Roblox Studio, but RSMM is not adding it to its own install of Studio. This is causing corescripts to break in play solo, making the CoreGui mostly unusable and bloating the output with errors.

**Comment by CloneTrooper1019** [comment]
Should be fixed now.

**Comment by Kampfkarren** [comment]
@CloneTrooper1019 Can confirmed, fixed after a forced client rebuild.
