### ISSUE TITLE
Feature Request: Only show FVariable warning once

### ISSUE THREAD

**Issue by EchoReaper** [CloneTrooper1019/Roblox-Studio-Mod-Manager#22]
I understand the potential consequences of editing flags after this warning has been displayed for the 500th time. Would be nice if it only showed the first time I opened the FVariable Editor, or if we're worried about users ignoring the warning the first time, FNIS from Skyrim has a similar popup where in addition to Yes/No would you like to continue, it has a "Cancel" option. Users don't habitually click "Cancel", and they have to read the warning to find out what the cancel option does.

**Comment by CloneTrooper1019** [comment]
I'll try to address this soon. Unfortunately the default windows prompt doesn't allow me to add a checkbox asking to never show the prompt again, so I might have to integrate my own message box to compensate.

**Comment by CloneTrooper1019** [comment]
Here ya go.
https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/commit/4ae68942ab8ae0bb17454431d5ed2d9c74601573
