### ISSUE TITLE
Bug: RSMM does not support logging in through browser

### ISSUE THREAD

**Issue by EchoReaper** [CloneTrooper1019/Roblox-Studio-Mod-Manager#23]
Studio may prompt the user to log in through the browser. When this occurs, RSMM does not handle it gracefully:

https://gfycat.com/ColorlessQuarrelsomeLeafcutterant

(this can be worked around by uninstalling RSMM, logging in, and then reinstalling)

**Comment by CloneTrooper1019** [comment]
Oof. I'll see what I can do.

**Comment by CloneTrooper1019** [comment]
Not 100% sure if this is fixed in the latest patch, but the data passed to the mod manager shouldn't be ignored. If it still appears to be happening let me know.

**Comment by CloneTrooper1019** [comment]
Can confirm this is fixed now.
