### ISSUE TITLE
Windows-only

### ISSUE THREAD

**Issue by LoganDark** [CloneTrooper1019/Roblox-Studio-Mod-Manager#24]
Really?

I mean, I'm pretty sure this is useful, but it's just another Windows-only program, making it completely useless for me and pretty much half the fucking world.

**Comment by EchoReaper** [comment]
Grow up and don't use such a bad OS then

**Comment by Kampfkarren** [comment]
I'm assuming you're a Mac user since Studio doesn't work on Linux (well). Have you tried running this with Mono or WINE?

**Comment by Kampfkarren** [comment]
The general topic of the issue seemed to be aggressive in that you're more angry than looking for a discussion ("it's just another Windows-only program, making it completely useless for me and pretty much half the fucking world.")

**Comment by LoganDark** [comment]
Oh, sorry about that. I'm autistic so I have trouble phrasing things in a non-aggressive way sometimes.

**Comment by CloneTrooper1019** [comment]
Developing cross-platform applications is tricky. The installation protocols of Roblox Studio are different between PCs and Macs, as well as the system architecture in general. I could possibly look into re-writing the entire program with a framework like Qt, but it would be a large undertaking that frankly I'm not sure I have the time or patience for right now.

**Comment by CloneTrooper1019** [comment]
Ultimately it comes down to the fact that I'm a Windows user. I originally wrote the tool for myself using the tools provided to make Windows applications. I'm not biased against Mac, it's just that making this work on a Mac would be an entirely different beast of a task.

**Comment by Kampfkarren** [comment]
@CloneTrooper1019 Getting it working cross platform is easier than you think with Mono, might be worth looking into.

**Comment by CloneTrooper1019** [comment]
I'll think about it.

**Comment by Dog2puppy** [comment]
@CloneTrooper1019 Are you still considering MacOS support?

**Comment by LoganDark** [comment]
@Dog2puppy Probably not, "I'll think about it" usually means "no and don't bother me again"

**Comment by CloneTrooper1019** [comment]
The idea is intriguing, but unfortunately I just don't have the experience with Macs or Mac development to really deliver such. If there is enough demand for it though, I may look into it sooner than later.
