### ISSUE TITLE
Repeatedly getting "Roblox Studio timed out" error when scanning FVariables

### ISSUE THREAD

**Issue by Hexcede** [CloneTrooper1019/Roblox-Studio-Mod-Manager#26]
I'm assuming it's because of the latest Roblox updates but I can't scan FVariables
Roblox Studio Build 0.351.0.232950 (Watch file 351)
Image: ![image](https://user-images.githubusercontent.com/8394472/44611180-c4ff4c80-a7cd-11e8-826c-f71f529fb7a7.png)
Version ID: version-1d1c92210a5a42f8
My solution would to parse your FVariable list from here: https://github.com/CloneTrooper1019/Roblox-Client-Watch/blob/master/FVariables.txt into the registry automatically and have the generation.
Here's a simple batch file to do just that in the meantime:
```cmd
@echo off



del FVariableScan.reg
echo Writing FVariables to reg file...
echo Windows Registry Editor Version 5.00>>FVariableScan.reg
echo.>>FVariableScan.reg
echo [HKEY_CURRENT_USER\Software\Roblox Studio Mod Manager\SavedFVariableScan]>>FVariableScan.reg
echo Wrote header
for /F "delims=" %%a in (FVariables.txt) do (
	echo "%%a"="">>FVariableScan.reg
	echo Wrote FVariable '%%a'
)
```
Usage:
Place FVariables.txt from your repository in the same place as the cmd file, run the cmd file and then open the generated reg file.

**Comment by CloneTrooper1019** [comment]
I’m aware of this bug. Will look into it soon.

**Comment by CloneTrooper1019** [comment]
I think this is fixed now. Are you still seeing it in the newest version?

**Comment by Hexcede** [comment]
Yes I can confirm it's now fixed! Thank you! 😄
