### ISSUE TITLE
Mod Manager will not open up at all

### ISSUE THREAD

**Issue by RodjGaming** [CloneTrooper1019/Roblox-Studio-Mod-Manager#27]
Ive had an older version of the mod manager(From Q1 2018) installed for a while now, but now out of my forgetfulness, I ran it while my AV was running and I was walking away from the computer, when I came back my AV deleted it, but I could not bring up my AV at all. I decided to download the new version of it, but I have tried everything and it will not come up at all. When I click on it, it gives me the loading mouse for a few seconds and then nothing happens after that. I have Windows 10 1803 on my computer.

**Comment by CloneTrooper1019** [comment]
Try this
1: Open regedit.exe
2: Navigate to HKEY_CURRENT_USER\Software
3: Delete the key called `Roblox Studio Mod Manager`
4: Run the program again

This *should* fix it. I'm going to investigate this issue further to see if there's anything I can do on my end to detect and diagnose it.

**Comment by RodjGaming** [comment]
Thanks, that fixed it.

**Comment by CloneTrooper1019** [comment]
Reopening so I can task a fix for this.

**Comment by CloneTrooper1019** [comment]
On second thought, there is an earlier ticket reporting this.
