### ISSUE TITLE
mods dont work

### ISSUE THREAD

**Issue by Thehelper104** [CloneTrooper1019/Roblox-Studio-Mod-Manager#30]
i tried this and it didn't work, can you fix it?

**Comment by Thehelper104** [comment]
once it finished, roblox studio was still the same

**Comment by CloneTrooper1019** [comment]
What did you modify?

**Comment by CloneTrooper1019** [comment]
I cannot fix problems unless you explicitly state what is broken. This description is vague nonsense.
