### ISSUE TITLE
Getting error when launching Studio

### ISSUE THREAD

**Issue by Swirln** [CloneTrooper1019/Roblox-Studio-Mod-Manager#35]
I downloaded the executable and pressed "Launch Roblox Studio." That's all I did.

![image](https://user-images.githubusercontent.com/25020307/50189152-bb07d900-02e9-11e9-8d89-da3350d36e9a.png)

Seems to happen when it patches the explorer icons. Clicking "Edit Explorer Icons" gives the same error.

Log from pressing Launch Roblox Studio: https://pastebin.com/7SJUj0aW
Log from pressing Edit Explorer Icons: https://pastebin.com/Wr2b0p3C

I don't know if this has to do with me having an older build of Roblox Studio Mod Manager installed on my computer. I removed it's folder from AppData, but it still gives me this error.

Any help would be greatly appreciated.

**Comment by CloneTrooper1019** [comment]
Investigating this now. I’ll see if I can reproduce it.

**Comment by CloneTrooper1019** [comment]
I wasn't able to reproduce the issue, but I think I've narrowed down what might have been triggering the exception. I have released a patched version.

If all goes well, this should stop the issue from happening. My only concern is that it might silently fail to get the explorer icon sprite sheet out of the exe. This will need some further investigation.

For now, try this new build and see if it continues to have problems.
https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/commit/8d05405f66e5aaecbe72498d61ca336881471b48

**Comment by carrot512** [comment]
Clicking Edit Explorer icons now gives an error.

![image](https://user-images.githubusercontent.com/25020307/50195678-c23ce000-0305-11e9-96ac-5df95b23dc03.png)

Logs: https://pastebin.com/u9DxfC6R

Other than that, launching seems to work fine.
Here's my specs in case you need them (windows version 1803): 
![image](https://user-images.githubusercontent.com/25020307/50195719-ebf60700-0305-11e9-88bb-dada9577d112.png)

**Comment by CloneTrooper1019** [comment]
Aha! I think I nailed down what the problem was!
Turns out `Encoding.Default` can differ between systems.

My system is using Windows-1252, so I updated the editor to explicitly use that.
https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/commit/e8eef51efb2e0da564e25c733af02545525947fa

**Comment by CloneTrooper1019** [comment]
Heyo, just wanted to follow up on this since I haven’t heard back from you.
Did my commit fix the problem on your end?
