### ISSUE TITLE
RSMM installs 32-bit Studio builds on 64-bit systems

### ISSUE THREAD

**Issue by UTMoStLimIt** [CloneTrooper1019/Roblox-Studio-Mod-Manager#37]
So a few weeks ago, 64-bit/AMD64 Studio for Windows has been released, however it seems that RSMM still installs 32-bit/x86 Studio builds onto a 64-bit system.

After installing Studio through RSMM (needed to test a FFlag) I found out that it was 32-bit studio that was installed and not 64-bit (both About Studio and Task manager stated that Studio was 32-bit).

While it isn't that big of an issue, it is a very big annoyance on my end (given that I have fairly large places and because of 32-bit studio being clamped to 4Gb of RAM max, I quickly hit that limit causing studio to hang).

**Comment by CloneTrooper1019** [comment]
Thanks for the heads up, I’ll investigate how Roblox is handling this.

**Comment by CloneTrooper1019** [comment]
Fixed! You can now opt into the 64-bit version or the 32-bit version. It will default to 64-bit if you are using a 64-bit OS.

https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/commit/8d61b66d46baa88a671a202024a3aced3e6adf52
