### ISSUE TITLE
please help me what is even happening

### ISSUE THREAD

**Issue by noblereign** [CloneTrooper1019/Roblox-Studio-Mod-Manager#40]
its just crashing and burning how do i fix this
https://www.youtube.com/watch?v=8JWEQBFAlaE

**Comment by noblereign** [comment]
update: i kind of fixed it by literally just copy-pasting the working studio (normal one) into the folder but now i have a different issue where version-switching  just isnt working

**Comment by noblereign** [comment]
another update: i fixed version switching but now steamvr doesnt work (the original reason i wanted to use this) so i guess just r.i.p

**Comment by CloneTrooper1019** [comment]
That’s odd. Was this the first time you used the program?

**Comment by noblereign** [comment]
nope i've used it many times before, but one day it just suddenly wouldn't open studio like at all, don't know why.. i mainly just used it because SteamVR worked on it (before)
