### ISSUE TITLE
When using the better icons mod, some icons are missing in Studio

### ISSUE THREAD

**Issue by UTMoStLimIt** [CloneTrooper1019/Roblox-Studio-Mod-Manager#41]
While using the "Better Icons" sample mod, I found something kinda odd to say the least:

- Some of the BasePart instances (CornerWedge....) have a blank icon (see attached screenshots)

- Keyframe Sequences have also no icons

I've attached a screenshot of the issue, I have not checked if other instances are also affected, but will update if I find the missing instances.

![Screenshot_129](https://user-images.githubusercontent.com/18629662/59159811-75c1a880-8acf-11e9-8e79-ab061ef1e15b.png)

**Comment by CloneTrooper1019** [comment]
It seems like the icon pack wasn’t loaded correctly. Did you paste the images into your ExplorerIcons directory while the icon editor window was open?

**Comment by UTMoStLimIt** [comment]
I pasted the icons before running the editor (FYI: I have never used it before...) I'm not sure what could be causing it.
