### ISSUE TITLE
Launcher should check for update on launch

### ISSUE THREAD

**Issue by LouieK22** [CloneTrooper1019/Roblox-Studio-Mod-Manager#43]
Since this project doesn't use releases, there is no way to watch releases. Therefore the only way to know when a new version releases is to routinely check the Github page. The launcher should automate this and check for the user when launched.

**Comment by CloneTrooper1019** [comment]
Agreed. I’ll be looking into this.

**Comment by CloneTrooper1019** [comment]
I guess the best option here would be to just start using releases.
Interfacing with GitHub's API would be annoying anyway.

**Comment by CloneTrooper1019** [comment]
Using releases now. Let me know if this is sufficient!
https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/releases

**Comment by LouieK22** [comment]
It would be sufficient if you posted the critical update as a release.
