### ISSUE TITLE
Use older versions of testlabs2

### ISSUE THREAD

**Issue by rossAPi** [CloneTrooper1019/Roblox-Studio-Mod-Manager#45]
Hi there,

Came from wanting to test VideoFrames etc. Just wondering if there is a way to go back to an older version of testlabs2, since they removed the video frame. 

Any help appreciated, thanksss!

**Comment by rossAPi** [comment]
Dang, someone needs to read these omg

**Comment by CloneTrooper1019** [comment]
Sorry, I saw this and was meaning to reply, but got sidetracked and forgot.
I’ll see what I can do.

**Comment by CloneTrooper1019** [comment]
Done! I've added a **Target Version** dropdown to the launcher window:

![image](https://user-images.githubusercontent.com/3926900/71407479-bb276c80-2600-11ea-8504-7e70a63a8e24.png)

You can use the following version on gametest2 to access VideoFrames:
`0.414.0.368784`

Release is available here:
https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/releases/tag/v2019.12.24
