### ISSUE TITLE
RSMM cannot open a file in Studio when the directory has a space in it

### ISSUE THREAD

**Issue by SundownMKII** [CloneTrooper1019/Roblox-Studio-Mod-Manager#47]
**What happens:**
RSMM cuts off the directory at the first space it finds when opening a file.

**Repro steps:**
* Create a directory with a space in it, e.g. `%UserProfile%/Desktop/Folder Space`
* Place a Studio file inside that directory
* Attempt to open the file using RSMM.
* RSMM will get as far as `%UserProfile%/Desktop/Folder`.

**Comment by CloneTrooper1019** [comment]
Extremely long overdue, but I finally got around to fixing this with the latest release!
Let me know if you still see it happening.
