### ISSUE TITLE
Registry keys are being overriden by the default ROBLOX installation

### ISSUE THREAD

**Issue by LucasWolschick** [CloneTrooper1019/Roblox-Studio-Mod-Manager#5]
When Roblox updates, the class keys in the registry are changed and attempting to edit a place in a browser opens the default Roblox Studio instead of the mod manager, thus requiring to manually go to the registry, change the keys and restart the computer.

**Comment by CloneTrooper1019** [comment]
I'll look into this. Thanks.

**Comment by CloneTrooper1019** [comment]
Are you only launching Studio from the mod manager itself?
Avoid Roblox's normal studio installer if you can.

**Comment by LucasWolschick** [comment]
Yes, I`m only launching studio from the mod manager: trying to open any place through the edit place button on any browser opens the default studio launcher instead. If I force a rebuild, it works temporarily until a Roblox update happens, when it starts opening the default .exe again.

**Comment by CloneTrooper1019** [comment]
Sorry if I've been putting this off a bit, I was just a little confused as to what you meant at first. I think I understand what you mean now so I just want to clarify real quick. So you're saying that when the normal Roblox player updates, it overwrites the registry values?

**Comment by LucasWolschick** [comment]
Yes: every time it updates I go to the registry and set the keys manually
to open the mod manager again, as they are overwritten to open the default
studio launcher each time.

Em 9 de jul de 2017 10:58, "CloneTrooper1019" <notifications@github.com>
escreveu:

**Comment by CloneTrooper1019** [comment]
Alright, I see now.
So unfortunately I'm not sure if there's much I can do to fix this unless I make the program run in the background when windows starts up, and then I constantly check the registry to see if an update is happening. I'll see what I can do though.

**Comment by CloneTrooper1019** [comment]
Alright hey, I think the issue should be addressed now, assuming everything works as intended.
Let me know if this issue persists!

https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/commit/5a7c804a6af84ad1a295b845a8614022da52be41

**Comment by LucasWolschick** [comment]
I tried uninstalling and reinstalling Roblox (the player) and running the mod manager, and turns out it works now! Thanks for the quick responses and attention on this.
