### ISSUE TITLE
Browser to studio plugin installation not working

### ISSUE THREAD

**Issue by GeneralScripter** [CloneTrooper1019/Roblox-Studio-Mod-Manager#50]
When trying to install a plugin from a browser, it will launch studio and install the plugin on vanilla studio. However, with this mod manager, it will open the launcher but after launching studio it does not install the plugin.

**Comment by Hexcede** [comment]
> This is due to how Roblox launches. RobloxStudioModManager essentially acts as the Roblox launcher, and based on a brief look at the code, the protocol changed, or RSMM doesn't support it. It does this because the normal Roblox launcher forces an install at its own folder, and RSMM has its own install functionality and install location.
> 
> The solution would need to be (re)implementing the plugin protocol.

https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/issues/57

**Comment by CloneTrooper1019** [comment]
I checked this again recently and it appears to be working fine.
If you can reproduce a case where it isn't working, please do let me know!
