### ISSUE TITLE
Editing FFlags no longer working.

### ISSUE THREAD

**Issue by UmbreonFR4** [CloneTrooper1019/Roblox-Studio-Mod-Manager#51]
I cannot seem to get any type of FFlags to work, I've tried a few things and i am unsure if this issue is just happening to me or other people as well.

**Comment by CloneTrooper1019** [comment]
Not seeing this issue on my end.

The program looks for flags in %localappdata%/Roblox/ClientSettings
By any chance, do multiple people use your PC? There’s a chance it could be getting stored in Program Files (x86) instead, which (if that’s the case) I should definitely fix.

**Comment by UmbreonFR4** [comment]
I mean the menu works fine but in studio it does not appear to do anything, ive tried using it both with the mod manager and with the manual way of putting the json in the roblox directory. My computer is a single user computer.

**Comment by CloneTrooper1019** [comment]
Closing this for now as I don’t have any repro information.
If you can identify what’s going on here, I’ll investigate further.
