### ISSUE TITLE
"Occamy.C" trojan appearing on every release except for the first one

### ISSUE THREAD

**Issue by CubicRalsei** [CloneTrooper1019/Roblox-Studio-Mod-Manager#58]
title

**Comment by CloneTrooper1019** [comment]
Duplicate of https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/issues/54

**Comment by CloneTrooper1019** [comment]
Make sure your Windows Defender definitions are up to date:
https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/issues/54
