### ISSUE TITLE
Dowloading a virus?

### ISSUE THREAD

**Issue by Hellooooooooooooo13** [CloneTrooper1019/Roblox-Studio-Mod-Manager#60]
Whenever I download this or run this, it says this is a virus according to my PC. The virus is [this](https://prnt.sc/s8ua6q), do recognize this file or at least know what this is?

**Comment by lighterlightbulb** [comment]
See: #54

**Comment by Hellooooooooooooo13** [comment]
Oh, sorry. Thank you!

**Comment by Hellooooooooooooo13** [comment]
I also dont know if this is because of the Mod Manager, but after I downloaded this the toolbox stopped working and some other things im not familiar. I've also restarted the studio multiple times.  The error message is that it cant load the module of the toolbox..
