### ISSUE TITLE
VideoFrame videos not showing outside of Roblox Studio

### ISSUE THREAD

**Issue by AKASGaming** [CloneTrooper1019/Roblox-Studio-Mod-Manager#62]
I use VideoFrame videos in my game and I noticed that the videos dont play anywhere outside of Roblox Studio (Launching the game from the roblox site). 

Is there something I need to do to fix this? a script?

**Comment by AlejandroDZ18** [comment]
The thing is your roblox studio is modded and Video frames are not released to public you just edited your roblox studio

one more question.. how did you install video frames on your studio?

**Comment by AKASGaming** [comment]
I followed [this tutorial](https://devforum.roblox.com/t/how-to-test-videoframe-in-studio-use-at-your-own-risk/499928) exactly

**Comment by CloneTrooper1019** [comment]
The feature is not available outside of Roblox Studio yet, as Roblox hasn't officially released it.
My mod manager provides you with tools to enable features early, but only locally on your machine and not in-game.
