### ISSUE TITLE
Roblox now loads scripts from a model.

### ISSUE THREAD

**Issue by GlowingUmbreon** [CloneTrooper1019/Roblox-Studio-Mod-Manager#66]
Since roblox now loads scripts from a model stored on the roblox website corescript mods will no longer work. This can be worked around by going into studio settings and enabling `Override Core Scripts` and setting `Override Core Scripts` to the directory of the core scripts. Adding a way to automatically enable this may be possible but I am unsure.

**Comment by GlowingUmbreon** [comment]
A way you may be able to automatically enable core scripts is on every mod manager launch copy registry keys from `Computer\HKEY_USERS\${userid}\Software\Roblox\RobloxStudio` to something like `Computer\HKEY_USERS\${userid}\Software\Roblox\RobloxModManager` and change the `ContentFolder` key
Although I am unsure if it is even possible for you to change what registry key roblox studio uses.

**Comment by GlowingUmbreon** [comment]
If you can figure out a way to sign rbxm files you may be able to replace the `\ExtraContent\models\DataModelPatch\DataModelPatch.rbxm` file

**Comment by AnthonyIsntHere** [comment]
So true
