### ISSUE TITLE
Attempting to load a version before v412 causes crash

### ISSUE THREAD

**Issue by higbead** [CloneTrooper1019/Roblox-Studio-Mod-Manager#69]
Attempting to load any version of studio before v412 results in the application crashing with a 403 error.

![image](https://user-images.githubusercontent.com/63697850/91602160-76db3180-e930-11ea-86cb-e74e332ff932.png)

Repro steps:
- Choose a target version of v411 or lower
- Click "**Launch Studio**"
- Observe crash

**Comment by CloneTrooper1019** [comment]
I think this is happening because Roblox has started archiving builds older than 3 months.
I'll see if I can update the program to reflect this pattern and cut off dates older than that.

**Comment by CloneTrooper1019** [comment]
Running a little late, but I got around to fixing this today.
Builds older than 90 days won't show up in the dropdown anymore.
