### ISSUE TITLE
Installer fails to apply FFlag configuration

### ISSUE THREAD

**Issue by devSparkle** [CloneTrooper1019/Roblox-Studio-Mod-Manager#7]
The installer is currently failing to apply FastFlag configuration. The installer only presents this issue when installed using the provided `.exe` file. Compiling the VS solution does not replicate this issue.

![screenshot 14](https://user-images.githubusercontent.com/6726742/28597641-f6e03e1c-7196-11e7-81cd-f8097e504463.png)

**Comment by CloneTrooper1019** [comment]
I think I might know whats going on, and I'm going to have a patch for it soon.
For now:
* Check "Just Open Studio" from the main window
* Create a folder called ClientSettings
* Create a file called ClientAppSettings.json
* Try again

**Comment by LouieK22** [comment]
Had the same issue. Tried given solution and it worked fine.

**Comment by CloneTrooper1019** [comment]
Should be fixed with this commit:
https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/commit/6bacd37de1dc0758f1949be1d7ea5e62b2733af4
