### ISSUE TITLE
could not start/install

### ISSUE THREAD

**Issue by XxHackerlolxX** [CloneTrooper1019/Roblox-Studio-Mod-Manager#71]
When i try to download it, it never starts up and it says there was a error installing it.

**Comment by CloneTrooper1019** [comment]
This isn't a lot of information for me to go off of.
Can you elaborate more on what the error says?

Your anti-virus software might be false-flagging it as malicious.

**Comment by shhshshhs** [comment]
To me when I try opening roblox studio mod manager it says this: 
https://gyazo.com/49e80084f42eca472fbd624a790041d1
I have no Idea how to fix it nor if it is related to the windows system virus protection.

**Comment by CloneTrooper1019** [comment]
Likely due to Windows virus protection nuking it 🙁

**Comment by LemonDoo** [comment]
Is there any fix for my windows defender flagging it as a virus?

I don't want to turn it off

**Comment by CloneTrooper1019** [comment]
@LemonDoo Boatbomber made a helpful guide for this:
https://twitter.com/BoatbomberRBLX/status/1347262909915738113
