### ISSUE TITLE
Qt5<multiple ones>.dll was not found

### ISSUE THREAD

**Issue by MobiusCraftFlip** [CloneTrooper1019/Roblox-Studio-Mod-Manager#72]
Whenever I click launch studio it always appears saying "The code execution cannot proceed because Qt5Quick.dll was not found. Reinstalling the program may fix this problem." I have downloaded it multiple times and it always says this. It says a similar error message every time but with different file names (QuickList, Qt5Qml.dll, Qt5Network.dll and Qt5Xml.dll)
Could somebody help me with this problem?

**Comment by MobiusCraftFlip** [comment]
I managed to fix those errors by putting the RobloxStudioModManager.exe into the roblox studio installation directory and now it is saying "This application failed to start because it could not find or load the qt platform plugin "windows" in "". Reinstalling the application may fix this problem.

**Comment by CloneTrooper1019** [comment]
Check the force reinstallation box and see if that fixes it. Sounds like it failed to download some files.
