### ISSUE TITLE
Norton LifeLock AV False Positive

### ISSUE THREAD

**Issue by bayceee** [CloneTrooper1019/Roblox-Studio-Mod-Manager#73]
It analyzes the file, and removes it. 
![image](https://user-images.githubusercontent.com/72530745/97986983-281e9d80-1da0-11eb-995b-f7fb69f70666.png)

**Comment by CloneTrooper1019** [comment]
There’s not a whole lot I can do about this unfortunately. 

The program technically exhibits the patterns of a Trojan because it installs and runs Roblox Studio’s exe, but it isn’t done in a malicious manner.

You’ll just have to manually whitelist it or turn off your antivirus.

**Comment by bayceee** [comment]
Oh thanks!
