### ISSUE TITLE
Can not find FFlag: VideoSupport

### ISSUE THREAD

**Issue by bayceee** [CloneTrooper1019/Roblox-Studio-Mod-Manager#74]
I searched it up, and it won't popup. I want to edit the flag.
![image](https://user-images.githubusercontent.com/72530745/99469499-76877c80-2908-11eb-8900-2b533ab13348.png)

**Comment by CloneTrooper1019** [comment]
They removed the flag because video support has fully shipped and a flag is no longer needed. It’s always enabled.
