### ISSUE TITLE
Google chrome flags it as virus now

### ISSUE THREAD

**Issue by Frenzyy-1** [CloneTrooper1019/Roblox-Studio-Mod-Manager#75]
Unable to install google chrome also blocks it.
![image](https://user-images.githubusercontent.com/72508034/103097506-6d45aa00-4642-11eb-8bdd-5df450def864.png)

**Comment by CloneTrooper1019** [comment]
Have you tried forking the repository through GitHub Desktop?

**Comment by CloneTrooper1019** [comment]
Let me know if this is still happening with the current version.
