### ISSUE TITLE
The example built in plugin is disfunctional

### ISSUE THREAD

**Issue by nsg-mfd** [CloneTrooper1019/Roblox-Studio-Mod-Manager#76]
Even when following all the steps, the only thing that seems to change is the icons, I have FFlagDoNotLoadUnverifiedBuiltInPlugins and FFlagVerifyBuiltInPlugins disabled, any way to fix this, or is it a global issue?

**Comment by CloneTrooper1019** [comment]
Ah whoops, I’ll update it soon.

**Comment by CloneTrooper1019** [comment]
Replaced the defunct plugin with `Service.rbxm`
