### ISSUE TITLE
Error when opening place through RobloxModManager

### ISSUE THREAD

**Issue by Nickuhhh** [CloneTrooper1019/Roblox-Studio-Mod-Manager#78]
This issue only occurs if I open the rbxl file with RobloxModManager. It seems to happen every time, but only to this specific file. The file opens file without having the mod manager as a middleman.

![image](https://user-images.githubusercontent.com/25470747/106537268-fe246680-64c7-11eb-81e8-4adbd9b79d48.png)

**Comment by CloneTrooper1019** [comment]
I think I know what’s going on here, someone reported this earlier but I still haven’t fixed it yet.
As a temporary workaround, make sure there’s no spaces in the file name or path.

**Comment by Nickuhhh** [comment]
@CloneTrooper1019 There is no spaces in the file name or path

**Comment by CloneTrooper1019** [comment]
Something is splitting the file name after the word `Billy`, there seems to be no file extension.
Are you sure there’s no special character that might be breaking it there?

**Comment by Nickuhhh** [comment]
@CloneTrooper1019 Yea, sorry I realized that it was called "Billy (1)", seems to make sense now.

**Comment by CloneTrooper1019** [comment]
This should be fixed now.
