### ISSUE TITLE
Asking to install .NET Core, even when installed

### ISSUE THREAD

**Issue by malizzar0** [CloneTrooper1019/Roblox-Studio-Mod-Manager#79]
I have .NET Core installed, directly from the link the error provides. I have tried restarting with no luck.
![windowsdesktop-runtime-3 1 11-win-x86_y8NZaCuHAX](https://user-images.githubusercontent.com/78530674/106864709-dd0e7200-668f-11eb-8bcf-452b8ca9490f.png)

**Comment by CloneTrooper1019** [comment]
I’m probably going to roll the project back to .NET Framrwork 4.7.2 while still keeping the new changes I made. Expect action on this very soon.

**Comment by CloneTrooper1019** [comment]
Let me know if this is still happening with the latest release.
I rolled it back to C# 7.3 and a .NET Framework 4.7.2 project!
