### ISSUE TITLE
Version changing is not working

### ISSUE THREAD

**Issue by LucasWolschick** [CloneTrooper1019/Roblox-Studio-Mod-Manager#8]
Hello again!

Yesterday I decided to test the gametest build of Studio, so I used the mod manager and launched it in gametest. After downloading everything that it needed, it launched studio but it wasn't running that version (given the changelogs in your other repo, there was supposed to be a property in skyboxes named "MoonTextureId", and it errored when changed from the command bar).

I tried rebuilding studio, but it also didn't work: I had to manually extract every .zip file in the downloads directory to the root folder to make it work in that version, when it worked.

After testing, I wanted to change back to the live build, but the same happened again. So, again, I went and extracted every .zip file in the downloads folder.

And sometimes, when changing from a newer version to the live version, Team Create becomes inaccessible, throwing a lot of errors of the kind "Type failed to learn x" and crashing studio (probably due to having a newer version).

I tried deleting every possible file left by the mod manager, including registry keys and logs, yet it still happens to me: I don't know if this only happens on my machine, couldn't test on other computers yet.

The default Roblox Studio works fine.

Thanks!

**Comment by CloneTrooper1019** [comment]
Yeah I've noticed there's something wrong with the file delta stuff. I'm going to investigate this further ASAP.

**Comment by CloneTrooper1019** [comment]
This issue should be fixed with the latest commit, let me know if there are any other issues!
https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/commit/6678da6c543684e433942c9a51f18e10cdf39de9

**Comment by CloneTrooper1019** [comment]
This issue should be fixed in the latest commit.
