### ISSUE TITLE
Many tools broken

### ISSUE THREAD

**Issue by RandomUser123451** [CloneTrooper1019/Roblox-Studio-Mod-Manager#80]
Many tools are broken in all versions of Roblox Studio. This only happens on the mod manager. Here is an example of the errors that appear on the output:

 Error: Plugin at C:/Users/Username/AppData/Local/Roblox Studio/BuiltInPlugins/ViewSelector.rbxm could not be verified and security settings prevent it from loading.

This issue started right after I updated the mod manager.

Also sorry for my bad English :(

**Comment by CloneTrooper1019** [comment]
Try forcing a reinstall with the force reinstall checkbox.

**Comment by RandomUser123451** [comment]
That didn't work.

**Comment by CloneTrooper1019** [comment]
Try the newest release and see if it still has problems.
https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/releases/tag/v2021.2.15

**Comment by RandomUser123451** [comment]
It still has the problem. I started thinking that the problem is with my computer because even the oldest Mod Manager version I used has the problem. There are also some problems outside of Roblox Studio that occur for similar reasons. I don't think I need to close this issue because Roblox Studio doesn't have this issue while Mod Manager has.

**Comment by CloneTrooper1019** [comment]
Try this:
1. Open regedit.exe
2. Navigate to HKEY_CURRENT_USER\SOFTWARE
3. Delete the key called `Roblox Studio Mod Manager`
4. Navigate to `%localappdata%`
5. Delete the `Roblox Studio` folder.
6. Run the mod manager again, let it fully install, and see if there are still any issues.

**Comment by RandomUser123451** [comment]
It works! Thanks!
