### ISSUE TITLE
Custom FFlags

### ISSUE THREAD

**Issue by FilteredStudio** [CloneTrooper1019/Roblox-Studio-Mod-Manager#83]
Its currently impossible to add custom FFlags that dont exist in the downloaded FFlag JSON file.

There are a few FFlags that aren’t in the JSON file that are declared at run time using ``game:DefineFastFlag()``

Its also possible to just directly edit the JSON file, but Mod Manager will undo any changes made to the file.

**Comment by CloneTrooper1019** [comment]
Resolved with https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/pull/87!
