### ISSUE TITLE
BuiltInPlugins wont work anymore

### ISSUE THREAD

**Issue by GalaxyBlueReal** [CloneTrooper1019/Roblox-Studio-Mod-Manager#86]
I had a plugin that allowed me to execute script at a higher level that used the BuiltInPlugins but this week I found that it kept getting not loaded for security mesures but before it loaded fine and when I was looking at the fflags "DoNotLoadUnverifiedBuiltInPlugins" and "VerifyBuiltInPlugins" there were not there anymore these 2 fflags allowed to disable the security mesures soo yea Im stuck with that rn

**Comment by CloneTrooper1019** [comment]
Roblox removed the flags unfortunately.
I'll be looking into whether it's possible to patch the exe around this, but otherwise I can't address it.

**Comment by CloneTrooper1019** [comment]
Get in touch on Twitter and I can show you a workaround.

**Comment by GalaxyBlueReal** [comment]
My Twitter tag is @mrsbobette06

**Comment by TR-MZ** [comment]
Hey! Is there still a workaround for this? Thanks!
My twitter is tr_mz_ °-°

**Comment by MaximumADHD** [comment]
Nope.

**Comment by GalaxyBlueReal** [comment]
> Hey! Is there still a workaround for this? Thanks! My twitter is tr_mz_ °-°

I found a way around this, I use internal studio. (Look command bar)

<img width="1710" alt="Image" src="https://github.com/user-attachments/assets/23a40ac2-68d7-4c5b-8f40-4f61d2f650af" />

Im using my own tool, because as of right now, there isn't any macOS Roblox Studio Internal Patcher and it's way easier to use than a patcher tbh.

But there is a public one, it's a patcher, only works on windows, try with caution, never really used it, only used my tool.
